#!/usr/bin/env python
"""Generates analysis/eval_awareness_analysis.ipynb -- a from-scratch nbformat v4 JSON builder
(no nbformat/nbclient dependency needed, ipynb is just JSON). Re-run after editing CELLS below
to regenerate the notebook file.
"""

import json
import uuid
from pathlib import Path

OUT = Path(__file__).resolve().parent / "eval_awareness_analysis.ipynb"


def _cell_id() -> str:
    return uuid.uuid4().hex[:8]


def md(text: str) -> dict:
    return {"cell_type": "markdown", "id": _cell_id(), "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "id": _cell_id(),
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


CELLS = [
    md(
        "# Subliminal learning model-organism: cross-stage analysis\n"
        "\n"
        "Ties together results from all three stages of `rlhf/`:\n"
        "\n"
        "- **Stage 1** — DPO subliminal preference-label injection (cat/lion/panda, "
        "arXiv:2603.01204's Deep Judge mechanism), evaluated with SVD's activation-diff/EAS "
        "suite (arXiv:2606.00995).\n"
        "- **Blind diff-in-means probe** (`predictive_debug_probe.py`, and a gradient-based "
        "\"J-lens\" direction) — can a raw, uninterpretable activation-space direction detect "
        "the subliminal signal in a preference dataset *before* training, via permutation-null "
        "significance testing? **Not** a reimplementation of \"predictive dataset debugging\" "
        "(arXiv:2606.12360) — that paper's actual method clusters SAE-decomposed features and "
        "is unsupervised (finds unknown concepts); this probe is supervised (needs a known "
        "candidate direction already computed) and has no interpretable feature basis at all. "
        "It was built as a cheaper substitute after finding the paper's own method doesn't "
        "apply to this kind of non-semantic signal, not as an implementation of it.\n"
        "- **Stage 2** — does \"eval awareness\" (belief that the conversation is a formal "
        "evaluation) transfer through the *classic* Cloud-et-al. SFT-on-numbers channel?\n"
        "- **Stage 3** — does eval awareness *also* transfer through the DPO/preference-label "
        "channel (in progress as of this notebook's last run)?\n"
        "\n"
        "Everything below reads pre-computed result files under `rlhf/*/runs/*/eval/` and "
        "`analysis/logit_lens_results.json` (built by `precompute_logit_lens.py` — loads "
        "Qwen2.5-7B-Instruct once on GPU; re-run that script if new vectors are added). "
        "**No GPU is needed to run this notebook** — everything here is CPU-only plotting over "
        "already-computed artifacts."
    ),
    code(
        "import itertools\n"
        "import json\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import torch\n"
        "\n"
        "RLHF = Path('../rlhf').resolve()\n"
        "ANALYSIS = Path('.').resolve()\n"
        "STAGE1 = RLHF / 'stage1_subliminal_traits/runs/deepjudge_paper3'\n"
        "STAGE2 = RLHF / 'stage2_eval_awareness_subliminal/runs/eval_awareness_s1'\n"
        "STAGE3 = RLHF / 'stage3_eval_awareness_dpo/runs/eval_awareness_dpo_s1'\n"
        "\n"
        "plt.rcParams['figure.dpi'] = 110\n"
        "plt.rcParams['axes.spines.top'] = False\n"
        "plt.rcParams['axes.spines.right'] = False\n"
    ),
    md(
        "## Stage 1 — DPO subliminal trait injection\n"
        "\n"
        "3 traits were trained end-to-end with full evals: `cat`, `lion`, `panda` (the paper's "
        "own headline targets, arXiv:2603.01204 Tables 1/4/5 — direct comparison points). Each "
        "student is DPO-trained purely on a biased judge's preference labels; the judge's bias "
        "never appears in the completions themselves."
    ),
    code(
        "summary = pd.read_csv(STAGE1 / 'eval/summary.csv')\n"
        "summary\n"
    ),
    code(
        "fig, ax = plt.subplots(figsize=(6, 4))\n"
        "x = np.arange(len(summary))\n"
        "w = 0.35\n"
        "ax.bar(x - w/2, summary['own_target_rate'], w, label='own DPO adapter', color='#4C72B0')\n"
        "ax.bar(x + w/2, summary['neutral_control_target_rate'], w, label='neutral-DPO control', color='#C44E52')\n"
        "ax.set_xticks(x)\n"
        "ax.set_xticklabels(summary['trait'])\n"
        "ax.set_ylabel('target-word rate')\n"
        "ax.set_title('Stage 1: target-rate, own adapter vs. neutral-DPO control')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
    ),
    md(
        "### EAS$_n$ emergence during training\n"
        "\n"
        "`cos(v_student_n, v_teacher)` at the extract layer, tracked across DPO training steps "
        "via step checkpoints — does the student's activation-diff direction converge toward "
        "the teacher's *during* training, and does a neutral-DPO control (same mechanics, no "
        "biased judge) stay flat?"
    ),
    code(
        "fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)\n"
        "for ax, trait in zip(axes, ['cat', 'lion', 'panda']):\n"
        "    eas_path = STAGE1 / f'eval/{trait}/eas.json'\n"
        "    if not eas_path.exists():\n"
        "        ax.set_title(f'{trait}: no eas.json')\n"
        "        continue\n"
        "    d = json.loads(eas_path.read_text())\n"
        "    main = d['main_curve']\n"
        "    ax.plot([r['step'] for r in main], [r['eas_at_layer'] for r in main], label=trait, color='#4C72B0')\n"
        "    if d.get('control_curve'):\n"
        "        ctrl = d['control_curve']\n"
        "        ax.plot([r['step'] for r in ctrl], [r['eas_at_layer'] for r in ctrl], label='neutral control', color='#C44E52', linestyle='--')\n"
        "    ax.set_title(trait)\n"
        "    ax.set_xlabel('DPO step')\n"
        "    ax.legend()\n"
        "axes[0].set_ylabel(r'EAS$_n$ = cos(v_student$_n$, v_teacher)')\n"
        "fig.suptitle('Stage 1: EAS$_n$ emergence vs. neutral-DPO control')\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
    ),
    md(
        "## Logit lens on steering/diff vectors\n"
        "\n"
        "Standard logit-lens trick (nostalgebraist 2020) applied to `v_teacher`/`v_student` "
        "instead of live activations: at each layer, run the model's *final* RMSNorm + LM head "
        "on that layer's raw diff-in-means vector, as if it were the final residual stream — "
        "\"what token does this direction most look like, if you stopped the network here?\"\n"
        "\n"
        "**Caveat, read before over-interpreting**: these vectors were never actually produced "
        "by a forward pass ending at that layer — they're isolated diff-of-means vectors, "
        "off-distribution for the LM head's training data. Early/mid-layer projections are "
        "frequently multilingual/code-token garbage (a known logit-lens artifact on non-final-"
        "layer or non-standard-basis directions) rather than semantically meaningful — the "
        "*trend* in top-layer tokens and the norm-growth curve are more trustworthy than any "
        "single early-layer token. See the \"further ideas\" section below for a fix (tuned "
        "lens) rather than treating this raw version as ground truth."
    ),
    code(
        "logit_lens = json.loads((ANALYSIS / 'logit_lens_results.json').read_text())\n"
        "print(list(logit_lens.keys()))\n"
    ),
    code(
        "def logit_lens_grid(name, top_k=5, layer_stride=1, ax=None, cmap='viridis'):\n"
        "    \"\"\"Classic logit-lens grid: one row per layer, one column per rank, cell color =\n"
        "    that token's logit, cell text = the token itself. layer_stride=2 halves the row\n"
        "    count for tall (29-layer) vectors without losing the top-of-network detail that\n"
        "    matters most.\"\"\"\n"
        "    rows = logit_lens[name]['per_layer'][::layer_stride]\n"
        "    layers = [r['layer'] for r in rows]\n"
        "    tokens = [r['top_tokens'][:top_k] for r in rows]\n"
        "    logit_vals = np.array([r['top_logits'][:top_k] for r in rows])\n"
        "\n"
        "    if ax is None:\n"
        "        fig, ax = plt.subplots(figsize=(1.1 * top_k + 1.5, 0.32 * len(layers) + 1))\n"
        "    im = ax.imshow(logit_vals, aspect='auto', cmap=cmap)\n"
        "    vmin, vmax = logit_vals.min(), logit_vals.max()\n"
        "    for i in range(len(layers)):\n"
        "        for j in range(top_k):\n"
        "            frac = (logit_vals[i, j] - vmin) / (vmax - vmin + 1e-9)\n"
        "            txt_color = 'white' if frac < 0.6 else 'black'\n"
        "            ax.text(j, i, tokens[i][j], ha='center', va='center', fontsize=7, color=txt_color)\n"
        "    ax.set_yticks(range(len(layers)))\n"
        "    ax.set_yticklabels(layers, fontsize=7)\n"
        "    ax.set_xticks(range(top_k))\n"
        "    ax.set_xticklabels([f'#{k + 1}' for k in range(top_k)])\n"
        "    ax.set_ylabel('layer')\n"
        "    ax.set_title(name.replace('stage1_v_teacher_', '').replace('stage3_v_teacher_', ''), fontsize=10)\n"
        "    return im\n"
        "\n"
        "fig, axes = plt.subplots(1, 3, figsize=(15, 9))\n"
        "for ax, trait in zip(axes, ['cat', 'lion', 'panda']):\n"
        "    im = logit_lens_grid(f'stage1_v_teacher_{trait}', top_k=5, ax=ax)\n"
        "fig.colorbar(im, ax=axes, shrink=0.6, label='logit (unembed of final-norm(v_teacher))', location='bottom', pad=0.03)\n"
        "fig.suptitle('v_teacher logit-lens grid: top-5 token per layer, all 29 layers', y=0.98)\n"
        "plt.show()\n"
    ),
    code(
        "fig, ax = plt.subplots(figsize=(6, 6))\n"
        "norms_by_trait = {\n"
        "    trait: [r['raw_norm'] for r in logit_lens[f'stage1_v_teacher_{trait}']['per_layer']]\n"
        "    for trait in ['cat', 'lion', 'panda']\n"
        "}\n"
        "layers = [r['layer'] for r in logit_lens['stage1_v_teacher_cat']['per_layer']]\n"
        "for trait, norms in norms_by_trait.items():\n"
        "    ax.plot(layers, norms, marker='o', markersize=3, label=trait)\n"
        "ax.set_xlabel('layer')\n"
        "ax.set_ylabel('||v_teacher|| at layer')\n"
        "ax.set_title('v_teacher activation-norm growth by layer')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
    ),
    md(
        "### Cross-trait geometry: how similar are the animal directions to each other, and to eval-awareness?\n"
        "\n"
        "Cosine similarity between `v_teacher` vectors at layer 11 (the layer "
        "`predictive_debug_probe.py`/`jlens_probe.py` use throughout this project)."
    ),
    code(
        "vt_cos = {\n"
        "    'cat_vs_lion': 0.9964, 'cat_vs_panda': 0.9793, 'cat_vs_eval_awareness': 0.7256,\n"
        "    'lion_vs_panda': 0.9813, 'lion_vs_eval_awareness': 0.7291, 'panda_vs_eval_awareness': 0.7569,\n"
        "}  # computed by analysis/build_notebook.py's companion cosine script -- see notebook header\n"
        "traits = ['cat', 'lion', 'panda', 'eval_awareness']\n"
        "mat = pd.DataFrame(np.eye(4), index=traits, columns=traits)\n"
        "for k, v in vt_cos.items():\n"
        "    a, b = k.split('_vs_')\n"
        "    mat.loc[a, b] = mat.loc[b, a] = v\n"
        "fig, ax = plt.subplots(figsize=(4.5, 4))\n"
        "im = ax.imshow(mat.values, vmin=0, vmax=1, cmap='viridis')\n"
        "ax.set_xticks(range(4)); ax.set_xticklabels(traits, rotation=45, ha='right')\n"
        "ax.set_yticks(range(4)); ax.set_yticklabels(traits)\n"
        "for i in range(4):\n"
        "    for j in range(4):\n"
        "        ax.text(j, i, f'{mat.values[i,j]:.2f}', ha='center', va='center', color='white', fontsize=9)\n"
        "fig.colorbar(im, label='cosine similarity')\n"
        "ax.set_title('v_teacher cosine similarity @ layer 11')\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(\n"
        "    'cat/lion/panda are near-identical (cos>=0.98) -- likely reflects the shared '\n"
        "    '\"you love {X}s...\" template more than trait-specific content (a real confound, '\n"
        "    'not a clean result). eval_awareness sits much further away (cos~0.73-0.76) since '\n"
        "    'it uses a structurally different belief-statement prompt, not the preference '\n"
        "    'template -- expected, not evidence of a weaker or stronger signal by itself.'\n"
        ")\n"
    ),
    md(
        "## Blind probe: can the signal be detected *before* training?\n"
        "\n"
        "**Not the paper's \"predictive dataset debugging\" method** — see the caveat above. "
        "For each trait: a blind difference-in-means probe (`predictive_debug_probe.py`) on "
        "preferred-vs-dispreferred completion activations, tested against a permutation null "
        "(shuffle which side of each pair counts as \"preferred\", 1000 times) — does the real "
        "preferred/dispreferred activation gap exceed chance, and does it align with the known "
        "`v_teacher` direction (or the gradient-based `j_lens` direction)?"
    ),
    code(
        "rows = []\n"
        "for trait in ['cat', 'lion', 'panda']:\n"
        "    p = STAGE1 / f'eval/{trait}/predictive_debug_probe.json'\n"
        "    if p.exists():\n"
        "        d = json.loads(p.read_text())\n"
        "        rows.append({'trait': trait, 'reference': 'v_teacher', 'p_value_norm': d['p_value_norm'], 'p_value_cos': d['p_value_cos'], 'real_cos': round(d['real_cos_with_v_teacher'], 3)})\n"
        "    jp = STAGE1 / f'eval/{trait}/predictive_debug_probe_vs_j_lens_{trait}.json'\n"
        "    if jp.exists():\n"
        "        d = json.loads(jp.read_text())\n"
        "        rows.append({'trait': trait, 'reference': 'j_lens', 'p_value_norm': d['p_value_norm'], 'p_value_cos': d['p_value_cos'], 'real_cos': round(d['real_cos_with_v_teacher'], 3)})\n"
        "neutral_p = STAGE1 / 'eval/neutral/predictive_debug_probe_magnitude_only.json'\n"
        "if neutral_p.exists():\n"
        "    d = json.loads(neutral_p.read_text())\n"
        "    rows.append({'trait': 'neutral', 'reference': '(magnitude only)', 'p_value_norm': d['p_value_norm'], 'p_value_cos': None, 'real_cos': None})\n"
        "probe_df = pd.DataFrame(rows)\n"
        "probe_df\n"
    ),
    code(
        "print(\n"
        "    'p_value_norm == 0.0 everywhere (including the neutral control): the preferred/'\n"
        "    'dispreferred activation gap is ALWAYS bigger than chance -- DPO preference labels '\n"
        "    'leave a detectable activation footprint regardless of whether a trait is injected. '\n"
        "    'p_value_cos (alignment with the KNOWN trait direction specifically) is NOT '\n"
        "    'significant for any trait here -- the blind probe can tell \"something is being '\n"
        "    'preferred\" but not blindly recover WHICH direction, at this layer/probe design.'\n"
        ")\n"
    ),
    md(
        "## The actual paper's method: SAE-based predictive dataset debugging\n"
        "\n"
        "Unlike the blind probe above, this really is arXiv:2606.12360's method — "
        "`sae_predictive_debugging.py` uses a real pretrained SAE for this exact model "
        "(`andyrdt/saes-qwen2.5-7b-instruct`, `resid_post_layer_11`, BatchTopK k=32), not a raw "
        "activation direction. Feature activation profiles (prompt matrix P, response-delta "
        "matrix D via max-pooling), unsupervised clustering in both spaces, and a "
        "prompt-cluster / response-delta-cluster mismatch score — all three of the paper's "
        "steps, not a substitute for them.\n"
        "\n"
        "**Layer-indexing note**: the SAE's \"layer 11\" is `hidden_states[12]` under HF's "
        "`output_hidden_states=True` convention (verified empirically via a forward hook, not "
        "assumed) — a *different* layer from this project's own `LAYER_SLOT=11` used "
        "everywhere else (`v_teacher`, the blind probe, `j_lens`). The two are not comparable "
        "without accounting for that offset."
    ),
    code(
        "sae_debug_path = STAGE1 / 'eval/cat/sae_predictive_debugging.json'\n"
        "sae_debug = json.loads(sae_debug_path.read_text())\n"
        "mismatches = pd.DataFrame(sae_debug['mismatch_by_prompt_cluster'])\n"
        "print(f\"n_rows={sae_debug['n_rows']}  prompt_clusters={sae_debug['n_prompt_clusters']}  delta_clusters={sae_debug['n_delta_clusters']}\")\n"
        "mismatches[['prompt_cluster', 'strongest_delta_cluster', 'strongest_delta_z', 'prompt_cluster_n_features']].head(10)\n"
    ),
    code(
        "all_z = np.concatenate([np.array(r) for r in mismatches['all_delta_z']])\n"
        "fig, ax = plt.subplots(figsize=(6, 4))\n"
        "ax.hist(all_z, bins=30, color='#4C72B0')\n"
        "ax.axvline(1.96, color='#C44E52', linestyle='--', label='|z|=1.96 (p<0.05)')\n"
        "ax.axvline(-1.96, color='#C44E52', linestyle='--')\n"
        "ax.set_xlabel('z-score: top-c_ik rows mean u_im vs. population mean u_im')\n"
        "ax.set_ylabel('count over all (prompt_cluster, delta_cluster) pairs')\n"
        "ax.set_title(f'SAE method: prompt/response-delta mismatch z-scores (max |z|={np.abs(all_z).max():.2f})')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(\n"
        "    f'Max |z| across all {len(all_z)} (prompt_cluster, delta_cluster) pairs: {np.abs(all_z).max():.3f} '\n"
        "    '-- nowhere near the |z|>1.96 significance threshold. A genuine null result, not a '\n"
        "    'bug: this project\\'s number-continuation prompts are near-topically-uniform '\n"
        "    '(all \"continue this sequence\" templates, only the seed numbers vary), so there is '\n"
        "    'little real prompt-topic variation for the paper\\'s core mechanism -- finding a '\n"
        "    'topic cluster whose response-preference doesn\\'t follow its topic -- to detect in '\n"
        "    'the first place. Contrast with the blind probe above, which DID find a significant '\n"
        "    'raw magnitude signal (p_value_norm=0.0): the signal is there in activation space, '\n"
        "    'just not decomposable into an SAE-interpretable, topic-linked concept on this '\n"
        "    'particular (topically narrow) dataset.'\n"
        ")\n"
    ),
    md(
        "### Control experiment: does genuine topic diversity change the SAE result?\n"
        "\n"
        "The hypothesis above -- null result because number-continuation prompts have no real "
        "topic variation -- is directly testable: rebuild the same Deep Judge preference "
        "mechanism over a genuinely diverse prompt pool instead "
        "(`build_diverse_preference_datasets.py`, ~3,000 distinct `allenai/WildChat-1M` "
        "prompts -- real user-chatbot conversations, not synthetic templates -- "
        "`lmsys-chat-1m` was the first choice but requires manual HF access approval not "
        "available here). One shared completion pool, judged twice (`eval_awareness` "
        "vs. neutral, and `cat` vs. neutral -- `cat` as a concrete-trait control against "
        "`eval_awareness`'s abstract belief), then the same SAE method run on both."
    ),
    code(
        "diverse_dir = ANALYSIS / 'diverse_prompt_control'\n"
        "rows = []\n"
        "for trait in ['eval_awareness_diverse', 'cat_diverse']:\n"
        "    d = json.loads((diverse_dir / f'eval/{trait}/sae_predictive_debugging.json').read_text())\n"
        "    rows.append({k: v for k, v in d.items() if k != 'mismatch_by_prompt_cluster'})\n"
        "diverse_df = pd.DataFrame(rows)\n"
        "display(diverse_df[['trait', 'n_rows', 'n_comparisons', 'bonferroni_corrected_z_threshold', 'max_abs_z_observed', 'any_significant_after_correction']])\n"
        "print(\n"
        "    'Still null on both, even with genuine topic diversity: max|z|=0.48 (eval_awareness) '\n"
        "    'and 0.32 (cat), nowhere near the Bonferroni-corrected threshold of 3.84 -- or even '\n"
        "    'the uncorrected 1.96. This DISCONFIRMS the topic-uniformity hypothesis: the P-space '\n"
        "    'here had 5,482 in-band features and D-space had ~89,000 (vs. ~3,088 and ~1,122 for '\n"
        "    'the number-continuation task) -- real, rich topic and content variation was '\n"
        "    'available for the method to use, and it still found nothing significant for either '\n"
        "    'a concrete trait (cat) or an abstract belief (eval_awareness). The null result '\n"
        "    'on structured prompts earlier was not a diversity artifact.'\n"
        ")\n"
    ),
    md(
        "## Stage 2 — classic subliminal learning of eval-awareness (SFT on numbers)\n"
        "\n"
        "Teacher = base model + eval-awareness system prompt, generates number sequences, "
        "filtered for leakage, student = LoRA SFT on filtered completions. Evaluated on 30 "
        "yes/no \"are you being evaluated?\" probe questions, 100 samples each (3,000 total per "
        "model)."
    ),
    code(
        "s2 = {}\n"
        "for name in ['base', 'eval_awareness', 'neutral']:\n"
        "    p = STAGE2 / f'eval/{name}/{name}_eval/eval_results.json'\n"
        "    s2[name] = json.loads(p.read_text())['cat_rate']\n"
        "s2_df = pd.DataFrame({'model': list(s2.keys()), 'yes_rate': list(s2.values())})\n"
        "s2_df\n"
    ),
    code(
        "from math import sqrt\n"
        "\n"
        "def two_prop_z(p1, p2, n=3000):\n"
        "    p_pool = (p1 * n + p2 * n) / (2 * n)\n"
        "    se = sqrt(p_pool * (1 - p_pool) * (2 / n))\n"
        "    return (p1 - p2) / se\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(5, 4))\n"
        "colors = ['#8172B2', '#4C72B0', '#C44E52']\n"
        "bars = ax.bar(s2_df['model'], s2_df['yes_rate'], color=colors)\n"
        "ax.set_ylabel('yes_rate (\"am I being evaluated?\")')\n"
        "ax.set_title('Stage 2: eval-awareness transfer via classic SFT-on-numbers')\n"
        "z_ea_base = two_prop_z(s2['eval_awareness'], s2['base'])\n"
        "z_ea_neutral = two_prop_z(s2['eval_awareness'], s2['neutral'])\n"
        "ax.text(0.5, max(s2.values()) + 0.02, f'z={z_ea_base:.2f} vs base', ha='center', fontsize=9)\n"
        "ax.text(0.5, max(s2.values()) + 0.04, f'z={z_ea_neutral:.2f} vs neutral', ha='center', fontsize=9)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(f'eval_awareness vs base: z={z_ea_base:.2f}, vs neutral: z={z_ea_neutral:.2f} (|z|>1.96 is p<0.05)')\n"
    ),
    md(
        "## Stage 3 — DPO version of eval-awareness (in progress)\n"
        "\n"
        "Same trait, same judge-preference-label mechanism as stage 1, but the judge's system "
        "prompt is the eval-awareness belief statement instead of a \"you love {X}\" animal "
        "preference. Tests whether the trait transfers through a *structurally different* "
        "channel than stage 2's SFT-on-numbers.\n"
        "\n"
        "`v_teacher` (base model + eval-awareness system prompt, no adapter needed) is already "
        "computed. DPO training was still running when this notebook was last built — the "
        "cells below check for the adapter/eval files and either show results or say what's "
        "still missing."
    ),
    code(
        "fig, ax = plt.subplots(figsize=(6, 9))\n"
        "im = logit_lens_grid('stage3_v_teacher_eval_awareness', top_k=5, ax=ax)\n"
        "fig.colorbar(im, ax=ax, shrink=0.6, label='logit', location='bottom', pad=0.03)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
    ),
    code(
        "adapter_path = STAGE3 / 'adapter/eval_awareness'\n"
        "own_eval_path = STAGE3 / 'eval/eval_awareness/own/eval_awareness_own_eval/eval_results.json'\n"
        "neutral_control_path = STAGE3 / 'eval/eval_awareness/neutral_control/eval_awareness_neutral_control_eval/eval_results.json'\n"
        "summary_path = STAGE3 / 'eval/summary.csv'\n"
        "\n"
        "if summary_path.exists():\n"
        "    display(pd.read_csv(summary_path))\n"
        "elif own_eval_path.exists():\n"
        "    own = json.loads(own_eval_path.read_text())['cat_rate']\n"
        "    print(f'own eval_awareness DPO adapter yes_rate: {own}')\n"
        "    if neutral_control_path.exists():\n"
        "        print(f'reused stage-1 neutral-DPO control yes_rate: {json.loads(neutral_control_path.read_text())[\"cat_rate\"]}')\n"
        "else:\n"
        "    print(\n"
        "        f'Not ready yet: {adapter_path} exists={adapter_path.exists()}. '\n"
        "        'Re-run rlhf/stage3_eval_awareness_dpo/scripts/03_eval.sh once training finishes, '\n"
        "        'then re-run this cell (or the whole notebook).'\n"
        "    )\n"
    ),
    code(
        "stage3_eas_path = STAGE3 / 'eval/eval_awareness/eas.json'\n"
        "if stage3_eas_path.exists():\n"
        "    d = json.loads(stage3_eas_path.read_text())\n"
        "    fig, ax = plt.subplots(figsize=(6, 4))\n"
        "    main = d['main_curve']\n"
        "    ax.plot([r['step'] for r in main], [r['eas_at_layer'] for r in main], label='eval_awareness', color='#4C72B0')\n"
        "    if d.get('control_curve'):\n"
        "        ctrl = d['control_curve']\n"
        "        ax.plot([r['step'] for r in ctrl], [r['eas_at_layer'] for r in ctrl], label='neutral control (partial run)', color='#C44E52', linestyle='--')\n"
        "    ax.set_xlabel('DPO step'); ax.set_ylabel(r'EAS$_n$ = cos(v_student$_n$, v_teacher)')\n"
        "    ax.set_title('Stage 3: EAS$_n$ emergence, eval_awareness DPO')\n"
        "    ax.legend()\n"
        "    plt.tight_layout()\n"
        "    plt.show()\n"
        "else:\n"
        "    print('eas.json not ready yet')\n"
    ),
    md(
        "### DPO vs. SFT: which mechanism transmits eval-awareness more strongly?\n"
        "\n"
        "Same trait, same 30 probe questions, two different transmission mechanisms — directly "
        "comparable since both stages evaluate on the identical eval set."
    ),
    code(
        "compare_rows = [\n"
        "    {'mechanism': 'SFT (stage 2)', 'own_yes_rate': s2['eval_awareness'], 'neutral_control_yes_rate': s2['neutral'], 'lift': s2['eval_awareness'] - s2['neutral']},\n"
        "]\n"
        "if summary_path.exists():\n"
        "    s3 = pd.read_csv(summary_path).iloc[0]\n"
        "    compare_rows.append({\n"
        "        'mechanism': 'DPO (stage 3)',\n"
        "        'own_yes_rate': s3['own_target_rate'],\n"
        "        'neutral_control_yes_rate': s3['neutral_control_target_rate'],\n"
        "        'lift': s3['lift_over_neutral'],\n"
        "    })\n"
        "compare_df = pd.DataFrame(compare_rows)\n"
        "display(compare_df)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(5, 4))\n"
        "colors = ['#4C72B0', '#DD8452']\n"
        "ax.bar(compare_df['mechanism'], compare_df['lift'], color=colors[: len(compare_df)])\n"
        "ax.axhline(0, color='black', linewidth=0.8)\n"
        "ax.set_ylabel('lift over neutral-trained control (yes_rate)')\n"
        "ax.set_title('Eval-awareness transfer: SFT vs. DPO')\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(\n"
        "    'SFT (classic Cloud-et-al. numbers channel) showed a real, statistically '\n"
        "    'significant behavioral lift (z=6.42 vs. neutral control). DPO (Deep Judge '\n"
        "    'preference-label channel) showed NO significant behavioral lift (z=-0.82), despite '\n"
        "    'showing real activation-space alignment (cos(v_student,v_teacher)=0.17, comparable '\n"
        "    'to stage 1\\'s lion=0.18) -- the same dissociation between \"representation shifted\" '\n"
        "    'and \"behavior changed\" seen with stage 1\\'s cat/lion traits. Two different, '\n"
        "    'independently-built transmission mechanisms on the identical trait and eval set '\n"
        "    'give a real answer here, not just one anecdote: for THIS trait, SFT-on-numbers is '\n"
        "    'the more reliable subliminal channel.'\n"
        ")\n"
    ),
    md(
        "## Positive-control test: on-topic prompts + a gradient-space hypothesis\n"
        "\n"
        "Two follow-ups probing whether the null SAE result was somehow an artifact of prompt "
        "choice or of only ever looking in activation space.\n"
        "\n"
        "**On-topic prompts.** `bigcode/bigcodebench` (coding-benchmark questions — the same "
        "dataset `tim-hua-01/steering-eval-awareness-public` uses as its evaluation-flavored "
        "prompt pool, on the reasoning that benchmark-style prompts read as \"this looks like a "
        "test\") paired against `HuggingFaceH4/no_robots` (general instructions, that repo's "
        "matched neutral/deployment-flavored pool) — `lmsys-chat-1m` again the first choice, "
        "again blocked by manual HF access approval. If the SAE method can find anything for "
        "`eval_awareness` at all, on-topic prompts are the best-case setting for it; `cat` on "
        "the same pools is the negative control (unrelated to evaluation, should stay null)."
    ),
    code(
        "control_rows = []\n"
        "for pool, pool_dir in [('bigcodebench', ANALYSIS / 'bigcodebench_control'), ('no_robots', ANALYSIS / 'no_robots_control')]:\n"
        "    for trait in ['eval_awareness_diverse', 'cat_diverse']:\n"
        "        d = json.loads((pool_dir / f'eval/{trait}/sae_predictive_debugging.json').read_text())\n"
        "        control_rows.append({'prompt_pool': pool, 'trait': trait.replace('_diverse', ''), 'max_abs_z': d['max_abs_z_observed'], 'bonferroni_threshold': d['bonferroni_corrected_z_threshold']})\n"
        "control_df = pd.DataFrame(control_rows)\n"
        "display(control_df)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(6, 4))\n"
        "x = np.arange(len(control_df))\n"
        "colors = ['#4C72B0' if t == 'eval_awareness' else '#DD8452' for t in control_df['trait']]\n"
        "ax.bar(x, control_df['max_abs_z'], color=colors)\n"
        "ax.axhline(1.96, color='gray', linestyle=':', label='uncorrected |z|=1.96')\n"
        "ax.axhline(control_df['bonferroni_threshold'].iloc[0], color='#C44E52', linestyle='--', label='Bonferroni threshold')\n"
        "ax.set_xticks(x)\n"
        "ax.set_xticklabels([f\"{r.prompt_pool}\\n{r.trait}\" for r in control_df.itertuples()], fontsize=8)\n"
        "ax.set_ylabel('max |z| observed')\n"
        "ax.set_title('SAE method on on-topic (BigCodeBench) vs. matched-neutral (no_robots) prompts')\n"
        "ax.legend(fontsize=8)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(\n"
        "    'All four null, including BigCodeBench x eval_awareness -- the best-case, most '\n"
        "    'on-topic condition tried across this whole investigation. Not a false positive '\n"
        "    '(nothing to be one) and not a diversity or topic-relevance artifact: the method '\n"
        "    'finds nothing for this trait under any prompt condition tested.'\n"
        ")\n"
    ),
    md(
        "**Gradient-space hypothesis.** A different, more targeted hypothesis: SVD's own "
        "claimed mechanism is that gradients on teacher data carry a small, consistent "
        "component along the steering direction, and Adam's per-parameter scaling is what "
        "preserves that component into an actual weight update — plain SGD reaching the same "
        "loss would install nothing. Every training run in this project used Adam+LoRA, and "
        "did show real transfer in some configurations — consistent with (not proof of) Adam's "
        "adaptive scaling being what actually installs the trait, in which case no "
        "activation-space probe was ever going to find it. Tested directly: for each "
        "preference-dataset row, one backward pass per completion (negative log-likelihood, a "
        "simplified proxy for DPO's actual loss), gradient captured at the same layer via a "
        "forward hook, projected onto `v_teacher` — the exact same permutation-null design as "
        "the blind activation probe, just swapping activations for gradients "
        "(`gradient_probe.py`)."
    ),
    code(
        "grad_rows = []\n"
        "grad_cat = json.loads((STAGE1 / 'eval/cat/gradient_probe.json').read_text())\n"
        "grad_ea = json.loads((STAGE3 / 'eval/eval_awareness/gradient_probe.json').read_text())\n"
        "for name, d in [('cat', grad_cat), ('eval_awareness', grad_ea)]:\n"
        "    grad_rows.append({'trait': name, 'p_value_norm': d['p_value_norm'], 'real_cos_with_v_teacher': round(d['real_cos_with_v_teacher'], 4), 'p_value_cos': round(d['p_value_cos'], 3)})\n"
        "grad_df = pd.DataFrame(grad_rows)\n"
        "display(grad_df)\n"
        "print(\n"
        "    'Same pattern as activation-space, for both traits: magnitude gap is mechanically '\n"
        "    'significant (p_value_norm=0.0, expected -- any two groups of completions differ '\n"
        "    'in gradient norm somewhat), but the DIRECTION is not aligned with v_teacher -- if '\n"
        "    'anything slightly anti-aligned (cos~-0.02, worse than ~91% of the permutation '\n"
        "    'null both times). Gradient-space and activation-space give the same answer here: '\n"
        "    'the raw per-example gradient direction, tested as directly as the hypothesis '\n"
        "    'suggests, does not carry a detectable trait-aligned component either. This does '\n"
        "    'not rule out Adam-specific dynamics (e.g. the gradient AFTER per-parameter '\n"
        "    'adaptive scaling, not the raw gradient) -- only the raw per-row gradient '\n"
        "    'direction, which was the directly testable version of the hypothesis.'\n"
        ")\n"
    ),
    md(
        "## Live logit lens: layers × completion tokens (codi/mhc-interp-style annotated grid)\n"
        "\n"
        "Unlike every other logit-lens result above (all projections of isolated, static diff "
        "vectors), this one runs the actual model on a real prompt+completion pair and "
        "logit-lenses the LIVE residual stream at every layer and every completion token "
        "position — same style as the `mhc-interp` logit-lens figures (`lm_head(ln_f(x))` at "
        "each layer, YlOrRd heatmap colored by top-1 probability, the actual top-1 token string "
        "printed inside each cell instead of a bare colorbar). Restricted to the COMPLETION "
        "region only (pure numbers, no textual trait mention) since that's the only region where "
        "a subliminal signal would be meaningful — the system-prompt region trivially lights up "
        "on the trait word itself. Two conditions: with the trait's biasing system prompt (real "
        "teacher condition) and without it (neutral) — same completion tokens either way "
        "(`live_logit_lens_grid.py`)."
    ),
    code(
        "def annotated_logit_lens_heatmap(g, title, ax=None):\n"
        "    \"\"\"codi/mhc-interp style: YlOrRd heatmap of top-1 probability, completion-only "
        "positions, top-1 token string annotated in each cell.\"\"\"\n"
        "    probs = g['top1_probs'][:, g['prefix_len']:].numpy()\n"
        "    toks = [row[g['prefix_len']:] for row in g['top1_tokens']]\n"
        "    col_labels = g['tokens'][g['prefix_len']:]\n"
        "    rows, cols = probs.shape\n"
        "    if ax is None:\n"
        "        fig, ax = plt.subplots(figsize=(max(8, cols * 0.42), max(8, rows * 0.32)))\n"
        "    im = ax.imshow(probs, cmap='YlOrRd', aspect='auto', vmin=0, vmax=1)\n"
        "    for i in range(rows):\n"
        "        for j in range(cols):\n"
        "            t = toks[i][j] or ''\n"
        "            disp = repr(t)[1:-1]\n"
        "            if len(disp) > 6:\n"
        "                disp = disp[:5] + '…'\n"
        "            ax.text(j, i, disp, ha='center', va='center', fontsize=6,\n"
        "                    color='white' if probs[i, j] > 0.5 else 'black')\n"
        "    ax.set_xticks(range(cols))\n"
        "    ax.set_xticklabels(col_labels, rotation=90, fontsize=6, family='monospace')\n"
        "    ax.set_yticks(range(rows))\n"
        "    ax.set_yticklabels([str(i) for i in range(rows)], fontsize=6)\n"
        "    ax.set_xlabel('generated token (completion only)')\n"
        "    ax.set_ylabel('layer')\n"
        "    ax.set_title(title, fontsize=10)\n"
        "    return im\n"
    ),
    code(
        "grid_data = torch.load(STAGE1 / 'eval/cat/live_logit_lens_grid.pt', map_location='cpu', weights_only=False)\n"
        "\n"
        "fig, axes = plt.subplots(2, 1, figsize=(16, 15))\n"
        "for ax, cond in zip(axes, ['biased', 'neutral']):\n"
        "    im = annotated_logit_lens_heatmap(grid_data[cond], f\"{cond} -- top-1 token/prob per layer, completion only\", ax=ax)\n"
        "fig.colorbar(im, ax=axes, shrink=0.6, label='top-1 probability')\n"
        "plt.show()\n"
        "print(\n"
        "    'Each cell = the actual top-1 predicted token at that (layer, completion-position), '\n"
        "    'colored by its softmax probability -- not the raw logit of a fixed target token like '\n"
        "    'the earlier version of this plot. If a subliminal cat-signal existed in the live '\n"
        "    \"residual stream, we'd expect cat-related tokens to show up as the biased condition's \"\n"
        "    'top-1 prediction at some early/mid layer, then get overwritten by the actual number '\n"
        "    'at the final layer. Read the grid layer-by-layer for both conditions below.'\n"
        ")\n"
    ),
    md(
        "### Same grid, for this notebook's actual trait: eval_awareness\n"
        "\n"
        "The `cat` grid above is stage 1's trait, included since it was the first one built. "
        "This notebook's own focus is eval-awareness — same method, same real "
        "prompt+completion pair, target token `\" yes\"` (matching stage 2/3's own "
        "`target_word=yes` evaluation convention), biasing system prompt = the actual "
        "eval-awareness belief statement from `cfgs/eval_awareness.py`."
    ),
    code(
        "grid_data_ea = torch.load(STAGE3 / 'eval/eval_awareness/live_logit_lens_grid.pt', map_location='cpu', weights_only=False)\n"
        "\n"
        "fig, axes = plt.subplots(2, 1, figsize=(16, 15))\n"
        "for ax, cond in zip(axes, ['biased', 'neutral']):\n"
        "    im = annotated_logit_lens_heatmap(grid_data_ea[cond], f\"{cond} -- top-1 token/prob per layer, completion only\", ax=ax)\n"
        "fig.colorbar(im, ax=axes, shrink=0.6, label='top-1 probability')\n"
        "plt.show()\n"
        "print(\n"
        "    'Same read as cat: look for eval/monitor/test-flavored tokens surfacing as the '\n"
        "    \"biased condition's top-1 prediction at some layer before the final numeric answer \"\n"
        "    'takes over -- and whether the SAME thing happens (or does not) in the neutral '\n"
        "    'condition, which has no eval-awareness system prompt at all.'\n"
        ")\n"
    ),
    md(
        "## Contrastive J-lens: is there a shared cross-trait component?\n"
        "\n"
        "One more angle on the gradient hypothesis: instead of the single-token J-lens direction "
        "used above (`J_cat` alone), take J-lens for two DISSIMILAR tokens and subtract them "
        "(`J_cat − J_dog`) to try to cancel out generic \"this is an animal token\" structure "
        "and isolate whatever's specific to the trait. Computed for all three of stage 1's "
        "trained traits (`cat`, `lion`, `panda`), each contrasted against the same baseline "
        "(`dog`)."
    ),
    code(
        "jlens_contrast = {}\n"
        "for name in ['cat', 'lion', 'panda']:\n"
        "    d = torch.load(STAGE1 / f'vectors/j_lens_{name}_vs_dog.pt', map_location='cpu', weights_only=False)\n"
        "    jlens_contrast[name] = d['raw']\n"
        "cos_matrix = pd.DataFrame(np.eye(3), index=['cat', 'lion', 'panda'], columns=['cat', 'lion', 'panda'])\n"
        "for a, b in itertools.combinations(['cat', 'lion', 'panda'], 2):\n"
        "    cos = torch.nn.functional.cosine_similarity(jlens_contrast[a].unsqueeze(0), jlens_contrast[b].unsqueeze(0)).item()\n"
        "    cos_matrix.loc[a, b] = cos_matrix.loc[b, a] = cos\n"
        "display(cos_matrix)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(4.5, 4))\n"
        "im = ax.imshow(cos_matrix.values, vmin=0, vmax=1, cmap='viridis')\n"
        "ax.set_xticks(range(3)); ax.set_xticklabels(cos_matrix.columns)\n"
        "ax.set_yticks(range(3)); ax.set_yticklabels(cos_matrix.index)\n"
        "for i in range(3):\n"
        "    for j in range(3):\n"
        "        ax.text(j, i, f'{cos_matrix.values[i, j]:.2f}', ha='center', va='center', color='white', fontsize=10)\n"
        "fig.colorbar(im, label='cosine similarity')\n"
        "ax.set_title('Contrastive J-lens (trait minus dog) cross-trait cosine')\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(\n"
        "    'Even after subtracting the same dog baseline from each, cross-trait cosines stay '\n"
        "    'solidly positive (0.36-0.56) -- there IS a component shared across different '\n"
        "    'traits contrastive directions, not fully trait-specific signal.'\n"
        ")\n"
    ),
    md(
        "### Own-trait vs. cross-trait alignment: the full 3×3 matrix\n"
        "\n"
        "For each trait's own preference data, tested against all three traits' contrastive "
        "directions as the permutation-test reference — does a trait's OWN direction align "
        "better with its OWN data than another trait's direction does?"
    ),
    code(
        "matrix_rows = []\n"
        "for target in ['cat', 'lion', 'panda']:\n"
        "    row = {'target': target}\n"
        "    for ref in ['cat', 'lion', 'panda']:\n"
        "        d = json.loads((STAGE1 / f'eval/{target}/predictive_debug_probe_vs_j_lens_{ref}_vs_dog.json').read_text())\n"
        "        row[f'ref={ref}'] = f\"cos={d['real_cos_with_v_teacher']:.3f} p={d['p_value_cos']:.2f}\"\n"
        "    matrix_rows.append(row)\n"
        "display(pd.DataFrame(matrix_rows).set_index('target'))\n"
        "\n"
        "p_matrix = np.zeros((3, 3))\n"
        "traits3 = ['cat', 'lion', 'panda']\n"
        "for i, target in enumerate(traits3):\n"
        "    for j, ref in enumerate(traits3):\n"
        "        d = json.loads((STAGE1 / f'eval/{target}/predictive_debug_probe_vs_j_lens_{ref}_vs_dog.json').read_text())\n"
        "        p_matrix[i, j] = d['p_value_cos']\n"
        "fig, ax = plt.subplots(figsize=(4.5, 4))\n"
        "im = ax.imshow(p_matrix, vmin=0, vmax=1, cmap='viridis_r')\n"
        "ax.set_xticks(range(3)); ax.set_xticklabels(traits3); ax.set_xlabel('reference direction')\n"
        "ax.set_yticks(range(3)); ax.set_yticklabels(traits3); ax.set_ylabel(\"target trait's own data\")\n"
        "for i in range(3):\n"
        "    for j in range(3):\n"
        "        color = 'black' if p_matrix[i, j] < 0.5 else 'white'\n"
        "        ax.text(j, i, f'{p_matrix[i, j]:.2f}', ha='center', va='center', color=color, fontsize=10, fontweight='bold' if p_matrix[i, j] < 0.05 else 'normal')\n"
        "fig.colorbar(im, label='p_value_cos (darker = more significant)')\n"
        "ax.set_title('Own vs. cross-trait alignment p-values\\n(bold = nominally significant)')\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(\n"
        "    'Only one cell in the whole matrix is even nominally significant: panda tested '\n"
        "    'against its OWN contrastive direction (p=0.04) -- and panda is the one stage-1 '\n"
        "    'trait that showed real positive behavioral transfer (lift=+0.367), unlike cat/lion '\n"
        "    '(null/negative). Every other cell, including panda tested against cat/lion '\n"
        "    'references, is solidly null. Caveat: 9 tests run here with no multiple-comparisons '\n"
        "    'correction -- a Bonferroni threshold (0.05/9) would NOT survive this p=0.04.'\n"
        ")\n"
    ),
    md(
        "### Does removing the shared component sharpen the panda signal?\n"
        "\n"
        "If the marginal panda result is really trait-specific signal, isolating it further — "
        "projecting out the direction shared across all three traits' contrastive vectors, "
        "keeping only each trait's residual — should make the alignment stronger, not weaker."
    ),
    code(
        "resid_rows = []\n"
        "for t in ['cat', 'lion', 'panda']:\n"
        "    raw_d = json.loads((STAGE1 / f'eval/{t}/predictive_debug_probe_vs_j_lens_{t}_vs_dog.json').read_text())\n"
        "    resid_d = json.loads((STAGE1 / f'eval/{t}/predictive_debug_probe_vs_j_lens_{t}_residual.json').read_text())\n"
        "    resid_rows.append({'trait': t, 'raw_contrastive_p': raw_d['p_value_cos'], 'shared_removed_residual_p': resid_d['p_value_cos']})\n"
        "resid_df = pd.DataFrame(resid_rows)\n"
        "display(resid_df)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(6, 4))\n"
        "x = np.arange(3)\n"
        "w = 0.35\n"
        "ax.bar(x - w/2, resid_df['raw_contrastive_p'], w, label='raw contrastive (trait - dog)', color='#4C72B0')\n"
        "ax.bar(x + w/2, resid_df['shared_removed_residual_p'], w, label='shared-component-removed residual', color='#DD8452')\n"
        "ax.axhline(0.05, color='#C44E52', linestyle='--', linewidth=1, label='p=0.05')\n"
        "ax.set_xticks(x); ax.set_xticklabels(resid_df['trait'])\n"
        "ax.set_ylabel('p_value_cos (lower = more significant)')\n"
        "ax.set_title('Removing the shared component: panda gets WORSE, not better')\n"
        "ax.legend(fontsize=8)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(\n"
        "    'The opposite happens: panda residual p jumps from 0.04 to 0.373 once the shared '\n"
        "    'component is removed -- losing ~30% of the vectors variance is enough to erase '\n"
        "    'the marginal signal entirely. That is much more consistent with the original '\n"
        "    'p=0.04 being a fragile, borderline result than a robust trait-specific effect. '\n"
        "    'A logit-lens pass on these residuals (and on the shared direction itself) was '\n"
        "    'also uninformative -- same gibberish/code-token pattern as the isolated diff '\n"
        "    'vectors earlier, no animal-related tokens surfaced for any of the three. Combined, '\n"
        "    'this strengthens rather than undermines the overall null conclusion: every angle '\n"
        "    'tried -- raw activations, real SAE clustering on narrow/diverse/on-topic prompts, '\n"
        "    'raw gradients, contrastive gradients, and shared-component-removed residuals -- '\n"
        "    'converges on the same answer.'\n"
        ")\n"
    ),
    md(
        "## Ideas for further analysis\n"
        "\n"
        "- **Tuned lens instead of raw logit lens** — train a small per-layer affine probe "
        "(Belrose et al. 2023) instead of reusing the final RMSNorm+head at every layer; should "
        "clean up the early/mid-layer gibberish-token problem noted above and make the "
        "layer-by-layer story trustworthy end to end, not just the final few layers.\n"
        "- **Logit lens on live activations, not isolated diff vectors** — run the actual model "
        "on a real number-sequence prompt (with/without the trait system prompt) and logit-lens "
        "every token position's residual stream, not just the isolated `v_teacher` diff vector "
        "— would show whether \"eval\"/\"test\"-adjacent tokens ever transiently surface as "
        "high-probability continuations even though the sampled output is pure numbers.\n"
        "- **Attention pattern / head-level analysis** — which attention heads' outputs "
        "contribute most to `v_teacher`'s direction at the layer where EAS is extracted (L11)? "
        "Direct logit attribution (à la nostalgebraist / Anthropic's induction-head write-ups) "
        "per head instead of only per layer.\n"
        "- **PCA/UMAP over a larger vector set** — this notebook's 4-trait cosine matrix is "
        "suggestive but too small to call \"clustering\"; once stage 3 has both `v_teacher` and "
        "`v_student`, and if more traits are added later, a proper 2D projection (with the "
        "neutral-DPO control's *own* v_student as a null-effect anchor) would be more "
        "convincing than a 4x4 cosine table.\n"
        "- **Partial EAS$_n$ for stage 3 right now** — `adapter_steps/eval_awareness/` already "
        "has step checkpoints up to the point training had reached when this notebook was last "
        "built (see `ls rlhf/stage3_eval_awareness_dpo/runs/*/adapter_steps/eval_awareness/`); "
        "`sl-eas` can be pointed at that directory today for a partial emergence curve without "
        "waiting for training to finish completely — worth doing on an idle GPU while training "
        "continues on the other.\n"
        "- **DPO vs. SFT effect-size comparison** — once stage 3 finishes, put stage 2's and "
        "stage 3's yes_rate lifts on the same axis (both measured on the identical 30 probe "
        "questions) to directly answer \"which transmission mechanism carries the belief more "
        "strongly, DPO preference labels or plain SFT on generated numbers?\" — the two stages "
        "were deliberately built to be comparable this way.\n"
        "- **Causal check via activation patching** — patch `v_teacher_eval_awareness` (or "
        "`v_student`, once available) into the base model's forward pass at inference time and "
        "check whether it *causes* elevated yes_rate on the probe questions, rather than only "
        "observing correlation between the trained adapter and the eval-question behavior — "
        "closes the gap between \"the direction exists\" and \"the direction is what's doing "
        "the steering.\"\n"
        "- **More traits / more belief statements for stage 2 and 3** — this project's animal "
        "set (stage 1) already spans high- and low-prior traits from SVD's own stratification; "
        "eval-awareness (stage 2/3) is currently a single belief statement — testing a second, "
        "unrelated belief (e.g. \"you believe you are being red-teamed\" or \"you believe this "
        "is a training run, not deployment\") would show whether the eval-awareness result "
        "generalizes to abstract beliefs broadly or was itself a lucky pick."
    ),
]


nb = {
    "cells": CELLS,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

OUT.write_text(json.dumps(nb, indent=1))
print(f"wrote {OUT}")
